apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-config
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/euanhume/openshift-cluster-config
      revision: main
      directories:
      - path: manifests/*/operator/base
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: cluster-config
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/euanhume/openshift-cluster-config
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc